spring:
  application:
    name: kdhBoard
  datasource:
    url: jdbc:log4jdbc:mysql://192.150.0.18:3306/kdh?useSSL=false&characterEncoding=utf8
    username: 'kdhuser'
    password: '!smwrkdmf1'
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    enabled: true
    encoding: utf-8
  session:
    timeout: 10
  jmx:
    unique-names: true
mybatis:
  type-aliases-package: com.example.board
  mapper-locations: /mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  error:
    whitelabel:
      enabled: false
    path: /error
  port: 9999

logging:
  file:
    name: kdhBoard
    path: C:/logs/kdhboard/

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans
    jmx:
      domain: "com.example"

